services:
  registrator:
    build: .
    image: registrator:latest
    hostname: registrator
    environment:
      REGISTRATOR_DOCKER_SOCKET: ${REGISTRATOR_DOCKER_SOCKET:-/var/run/docker.sock}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${REGISTRATOR_DOCKER_SOCKET:-/var/run/docker.sock}:ro
    ports:
      - "5555:5555/udp"
    restart: unless-stopped
